name: sono
description: "Local music player"
publish_to: 'none'

version: 1.0.9-beta+10009

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  # Custom packages
  sono_refresh:
    # path: ../../plugins/sono_refresh
    git:
      url: https://github.com/appsono/sono_refresh
      ref: v1.0.0

  # UI & visuals
  cupertino_icons: ^1.0.8
  flutter_blurhash: ^0.9.1
  flutter_svg: ^2.0.10+1
  marquee: ^2.3.0
  shimmer: ^3.0.0
  flutter_markdown_plus: ^1.0.7
  animated_icon: ^1.0.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  scrollable_positioned_list: ^0.3.8
  flutter_screenutil: ^5.9.3

  # State & utils
  provider: ^6.1.5+1
  async: ^2.13.0
  logging: ^1.3.0
  rxdart: ^0.28.0
  intl: ^0.20.2
  pub_semver: ^2.2.0
  vector_math: ^2.1.4
  yaml: ^3.1.3
  path: ^1.9.1
  crypto: ^3.0.6

  # Audio
  just_audio: ^0.9.40
  just_audio_mpv: ^0.1.7 # discontinued
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: any
  on_audio_query:
    #path: ../../plugins/on_audio_query/packages/on_audio_query
    git:
      url: https://github.com/appsono/on_audio_query.git
      path: packages/on_audio_query
      ref: v2.9.8.1
  audio_service: ^0.18.18

  # Device & storage
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3

  # System & notifications
  flutter_local_notifications: ^19.4.1
  url_launcher: ^6.3.1
  app_links: ^7.0.0
  share_plus: ^12.0.0

  # Networking
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  network_info_plus: ^7.0.0

  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # Analytics
  firebase_analytics: ^12.0.3

  # Misc
  http_parser: ^4.1.2
  mime: ^2.0.0
  image: ^4.3.0
  sqflite: ^2.4.2

  # Environment configuration
  flutter_dotenv: ^6.0.0
  sqflite_common_ffi: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_legacy.png"
  adaptive_icon_background: "#ff4893"
  adaptive_icon_foreground: "assets/icon/adaptive_foreground.png"
  adaptive_icon_monochrome: "assets/icon/adaptive_monochrome.png"

  android_beta:
    android: true
    image_path: "assets/icon/ic_launcher_beta.png"
    adaptive_icon_background: "#ff4893"
    adaptive_icon_foreground: "assets/icon/ic_launcher_beta.png"
    adaptive_icon_monochrome: "assets/icon/ic_launcher_beta_monochrome.png"
    flavor: beta

  android_nightly:
    android: true
    image_path: "assets/icon/ic_launcher_nightly.png"
    adaptive_icon_background: "#ff4893"
    adaptive_icon_foreground: "assets/icon/ic_launcher_nightly.png"
    adaptive_icon_monochrome: "assets/icon/ic_launcher_nightly_monochrome.png"
    flavor: nightly

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logos/
    - assets/images/emojis/
    - assets/icon/
    - assets/icons/
    - pubspec.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
          weight: 400
